const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const db={dennis:{xp:300,rewardBaseXp:0,words:[{id:'a'}]},yura:{xp:100,rewardBaseXp:0,words:[]},'session-dennis':{token:'d',expires:Date.now()+86400000},'session-yura':{token:'y',expires:Date.now()+86400000}};let lose=false;
function context(file){const ctx=vm.createContext({window:{},navigator:{},Date,Intl,Math,crypto:require('crypto').webcrypto,AbortController,setTimeout,clearTimeout,fetch:async(url,opt={})=>{const key=url.split('/').at(-1);if(opt.method==='POST'){db[key]=JSON.parse(opt.body);if(lose){lose=false;throw Error('Lost response');}return {ok:true};}return {ok:true,status:db[key]?200:404,json:async()=>structuredClone(db[key])};}});vm.runInContext(fs.readFileSync(file,'utf8'),ctx);return ctx.window.Quest;}
(async()=>{const Q=context('dennis-yura-vocab/quest.js'),poop=context('alpine-reward/quest.js'),original=structuredClone(db.dennis);
await Q.start('DENNIS','d','f1','flight');const stamp=db['games-dennis'].flightPlayedAt;assert.ok(stamp);assert.equal(db['games-yura'],undefined);assert.deepEqual(db.dennis,original);
await Q.start('DENNIS','d','f1','flight');assert.equal(db['games-dennis'].spent,1);await poop.start('DENNIS','d','p1');assert.equal(db['games-dennis'].spent,2);assert.equal(db['games-dennis'].flightPlayedAt,stamp);
lose=true;await assert.rejects(Q.start('DENNIS','d','f2','flight'));await Q.start('DENNIS','d','f2','flight');assert.equal(db['games-dennis'].spent,3);
for(let i=0;i<3;i++)await Q.start('DENNIS','d','next'+i,'flight');assert.equal((await Q.status('DENNIS','d')).canPlay,false);assert.equal((await Q.status('DENNIS','d')).remaining,3);await assert.rejects(Q.start('DENNIS','d','blocked','flight'),/Daily limit/);
db['games-dennis'].day='2000-01-01';await Q.start('DENNIS','d','tomorrow','flight');assert.equal(db['games-dennis'].usedToday,1);assert.equal(db['games-dennis'].flightPlayedAt,stamp);
for(let i=0;i<3;i++)await Q.start('YURA','y','y'+i,'flight');await assert.rejects(Q.start('YURA','y','y-no','flight'),/Earn 100 XP/);assert.equal(db['games-yura'].spent,3);await assert.rejects(Q.start('DENNIS','wrong','bad','flight'),/expired/);
const html=fs.readFileSync('alpine-reward/index.html','utf8'),game=fs.readFileSync('alpine-reward/game.js','utf8');assert.equal(game.includes('localStorage'),false);assert.equal(html.includes('PERSONAL BEST'),false);assert.equal(html.includes('leaderboard'),false);assert.equal(fs.readFileSync('alpine-reward/quest.js','utf8'),fs.readFileSync('dennis-yura-vocab/quest.js','utf8'));
console.log('PASS: shared quota, account-specific NEW, Poop preserves NEW state, no double charge on lost response, daily cap and carry-over, no flight records, unchanged vocabulary/XP.');})().catch(e=>{console.error(e);process.exitCode=1});
