const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(require('path').join(__dirname,'../dennis-yura-vocab/matching.js'),'utf8').replace('return {setup,leave,pairPool,choosePairs};','return {setup,leave,pairPool,choosePairs,select,save,seed(){mode="memory";phase="play";round=[{id:"a",word:"one",meanings:["一"]},{id:"b",word:"two",meanings:["二"]}];cards=[{id:"a",side:"en"},{id:"a",side:"meaning"},{id:"b",side:"en"},{id:"b",side:"meaning"}];},state(){return {matched:matched.size,earned,waiting,queue:saveQueue.length};}};');
function harness(storage={}){const elements=new Map(),timers=[];let resolveSave,fail=false,uid=0;const db={xp:0,answers:{}};const el=()=>({classList:{contains:()=>false,add(){},remove(){},toggle(){}},replaceChildren(){},append(){},setAttribute(){},dataset:{}});const ctx={window:{},localStorage:{getItem:k=>storage[k],setItem:(k,v)=>storage[k]=v},document:{createElement:el,createTextNode:()=>el()},$:id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id);},session:{user:'DENNIS',token:'test'},busy:false,currentData:null,setTimeout:(f,ms)=>{timers.push({f,ms});return timers.length;},clearTimeout(){},Date,Set,Q:{uid:()=>String(++uid),day:()=> '2026-10-10',auth:async()=>{},update:async(user,fn)=>{await new Promise(r=>resolveSave=r);fn(db);if(fail){fail=false;throw Error('response lost');}return db;},recordAnswer:(d,a)=>{if(!d.answers[a.id]){d.answers[a.id]={award:a.ok?10:0};d.xp+=a.ok?10:0;}}}};vm.createContext(ctx);vm.runInContext(source,ctx);const m=ctx.window.MatchPractice;m.seed();return {m,db,storage,timers,elements,release:()=>resolveSave(),fail:()=>fail=true};}
const tick=()=>new Promise(r=>setImmediate(r));
(async()=>{const h=harness();h.m.select(0);h.m.select(1);assert.equal(h.m.state().matched,1,'correct pair immediately matched before server');await tick();h.m.select(2);h.m.select(3);assert.equal(h.m.state().matched,2,'next pair playable while saving');assert.equal(h.m.state().queue,2);h.fail();h.release();await tick();assert.equal(h.m.state().queue,2,'failure retains both attempts');assert.equal(h.db.xp,10);h.m.save();await tick();h.release();await tick();assert.equal(h.db.xp,20,'lost response retry is idempotent');assert.equal(h.m.state().queue,0);assert.equal(h.m.state().earned,20);
const w=harness();w.m.select(0);w.m.select(3);assert.equal(w.timers[0].ms,500);w.timers[0].f();assert.equal(w.m.state().waiting,null,'wrong pair closes independently of server');await tick();w.m.leave();w.release();await tick();assert.equal(w.m.state().earned,0,'old round response cannot affect another screen');
const same=harness();same.m.select(0);same.m.select(2);assert.equal(same.m.state().queue,0,'same language pair has no vocabulary penalty');assert.equal(same.timers[0].ms,500);
const restored=harness(h.storage);assert.equal(restored.m.state().queue,0);
const pending=harness();pending.m.select(0);pending.m.select(1);const reload=harness(pending.storage);assert.equal(reload.m.state().queue,1,'unsaved attempt survives reload');
console.log('PASS: immediate matching, continued play during save, 500ms wrong-card closing, lost-response retry, ordered writes, navigation isolation, same-language pairs, persistent pending attempts.');})().catch(e=>{console.error(e);process.exitCode=1;});

