
'use strict';
const Q=window.Quest,$=id=>document.getElementById(id);
const views=['profiles','pin','home','add','words','practice','quiz','match'];
let session=null,currentData=null,pinUser=null,pin='',busy=false,rankTab='learning';
let quiz=[],quizIndex=0,results=[],answered=true,hinted=false,deadline=0,timerId=null,pending=null,retries=[];
let lastHomeDay=Q.day();
setInterval(()=>{if(session&&Q.day()!==lastHomeDay){lastHomeDay=Q.day();if(!$('homeView').classList.contains('hidden'))refresh();}},30000);
const name=u=>u==='PARENT'?'Parent':u[0]+u.slice(1).toLowerCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function show(view){if(window.MatchPractice)window.MatchPractice.leave();clearInterval(timerId);answered=true;views.forEach(v=>$(v+'View').classList.toggle('hidden',v!==view));$('signOut').classList.toggle('hidden',!session);if(view==='home')refresh();if(view==='words')renderWords();if(view==='quiz')setupQuiz();if(view==='practice')window.MatchPractice.setup();window.scrollTo(0,0);}
function loggedOut(){session=null;currentData=null;sessionStorage.removeItem('questSession');show('profiles');}
function pinScreen(user){pinUser=user;pin='';$('pinGreeting').textContent=user==='PARENT'?'Parent access':'Hi, '+name(user)+'!';$('pinCaption').textContent=user==='PARENT'?'Enter your parent password.':'Enter your 4-digit PIN.';$('loginError').textContent='';show('pin');drawPin();}
function drawPin(){const n=pinUser==='PARENT'?8:4;$('pinDots').innerHTML=Array.from({length:n},(_,i)=>'<span class="dot'+(i<pin.length?' filled':'')+'"></span>').join('');}
async function enterDigit(value){if(busy||$('pinView').classList.contains('hidden'))return;if(value==='Backspace')pin=pin.slice(0,-1);else if(/^\d$/.test(value))pin+=value;drawPin();const size=pinUser==='PARENT'?8:4;if(pin.length!==size)return;busy=true;try{session=await Q.login(pinUser,pin);sessionStorage.setItem('questSession',JSON.stringify(session));pin='';show('home');}catch(e){pin='';drawPin();$('loginError').textContent=e.message;}finally{busy=false;}}
for(const value of ['1','2','3','4','5','6','7','8','9','','0','Backspace']){const b=document.createElement('button');b.textContent=value==='Backspace'?'⌫':value;b.disabled=!value;b.setAttribute('aria-label',value==='Backspace'?'Delete digit':value||'Empty');b.onclick=()=>enterDigit(value);$('keypad').append(b);}
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>pinScreen(b.dataset.profile));
$('pinBack').onclick=()=>{if(!busy)show('profiles');};$('parentAccess').onclick=()=>{if(!busy){loggedOut();pinScreen('PARENT');}};
$('signOut').onclick=()=>{if(!busy)loggedOut();};
document.addEventListener('keydown',e=>{if(!$('pinView').classList.contains('hidden')&&(/^\d$/.test(e.key)||e.key==='Backspace')){e.preventDefault();enterDigit(e.key);}});
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{if(session&&!busy)show(b.dataset.open);});
document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>{if(!busy)show('home');});
function mastery(w){const attempts=(w.correct||0)+(w.wrong||0),rate=(w.correct||0)/Math.max(1,attempts);return attempts>=5&&rate>=.8?'MASTERED':attempts>=2&&rate>=.5?'FAMILIAR':'LEARNING';}
function streak(words){const dates=new Set(words.map(w=>w.addedDate));let cursor=new Date(Q.day()+'T12:00:00+08:00'),n=0;if(!dates.has(Q.day(cursor)))cursor.setUTCDate(cursor.getUTCDate()-1);while(dates.has(Q.day(cursor))&&n<1000){n++;cursor.setUTCDate(cursor.getUTCDate()-1);}return n;}
async function refresh(){if(!session)return;const s=session;$('homeError').textContent='';$('playGame').disabled=true;try{await Q.auth(s.user,s.token);const [data,l]=await Promise.all([Q.load(s.user),Q.ledger(s.user)]);if(session!==s)return;currentData=Q.init(data);const r=Q.reward(data,l);$('greeting').textContent='Hi, '+name(s.user)+'!';$('parentBanner').classList.toggle('hidden',s.user!=='PARENT');$('xp').textContent=(data.xp||0)+' XP';$('level').textContent=Math.floor((data.xp||0)/100)+1;$('wordCount').textContent=data.words.length;const mission=data.words.some(w=>w.addedDate===Q.day());$('dailyMission').textContent=mission?'✓ Daily mission complete. Keep adding more words!':'Today’s mission: add at least one new word.';$('streak').textContent=streak(data.words);$('rewardProgress').style.width=r.progress+'%';$('rewardText').textContent=r.progress+' / 100 XP to your next 3 plays'+(r.remaining>6?' / Extra earned plays are banked.':'');$('gameStatus').textContent=r.available+' plays left / '+r.used+'/6 played today';$('gameNote').textContent=r.used>=6?'Daily limit reached. Come back tomorrow!':!r.remaining?'Earn 100 XP to unlock 3 plays.':'One play is used when a new game starts. Unused plays carry over.';$('playGame').disabled=!r.canPlay;$('meaningLabel').textContent=s.user==='PARENT'?'Meaning(s)':'Chinese Meaning(s)';$('meaningHint').textContent=s.user==='PARENT'?'Korean meanings are welcome. Separate meanings with / or new lines.':'Enter simplified Chinese meanings, separated by / or new lines.';const weak=[...data.words].filter(w=>w.wrong).sort((a,b)=>(b.wrong||0)-(a.wrong||0)).slice(0,5);$('weakList').textContent=weak.length?weak.map(w=>w.word+' / '+w.meanings.join(' / ')).join('\n'):'No missed words yet.';await renderLeaderboard();}catch(e){if(session===s)$('homeError').textContent=e.message;}}
$('playGame').onclick=async()=>{if(!session||$('playGame').disabled||busy)return;busy=true;$('playGame').disabled=true;try{const r=await Q.status(session.user,session.token);if(!r.canPlay){await refresh();return;}location.href=Q.GAME+'?user='+encodeURIComponent(session.user)+'&token='+encodeURIComponent(session.token);}catch(e){$('homeError').textContent=e.message;}finally{busy=false;}};
$('learningTab').onclick=()=>{rankTab='learning';renderLeaderboard();};$('gameTab').onclick=()=>{rankTab='game';renderLeaderboard();};
function levelBadge(xp){const level=Math.max(1,Math.floor((xp||0)/100)+1),tier=Math.min(8,Math.floor((level-1)/10)),positions=[[38,34],[126,34],[38,112],[126,112],[38,192],[126,192],[38,273],[126,273],[38,363]],[left,top]=positions[tier];return '<span class="level-badge" aria-label="Level '+level+'"><svg class="crown-icon" viewBox="'+left+' '+top+' 72 66" aria-hidden="true"><image href="crowns.svg" width="236" height="470"/></svg><span class="level-label">Lv. '+level+'</span></span>';}
async function renderLeaderboard(){const tab=rankTab;$('learningTab').classList.toggle('active',tab==='learning');$('gameTab').classList.toggle('active',tab==='game');$('leaderboard').textContent='Loading...';try{let rows;if(tab==='learning'){rows=await Promise.all(['DENNIS','YURA'].map(async u=>({user:u,name:name(u),score:(await Q.load(u)).xp||0})));rows.sort((a,b)=>b.score-a.score);}else{const ns='dy-poop-dodge-79ae04b9-021f-4208-aec7-46c68d01e86f';const buckets=await Promise.all([0,1,2,3].map(async i=>{const r=await fetch(Q.BASE+'/'+ns+'/scores-'+i,{cache:'no-store'});if(r.status===404)return {};if(!r.ok)throw Error('Could not load game scores.');return r.json();}));rows=buckets.flatMap(b=>Object.values(b)).filter(r=>r&&typeof r.name==='string'&&Number.isInteger(r.score)&&Number.isFinite(r.at)).sort((a,b)=>b.score-a.score||a.at-b.at).slice(0,10);}if(tab!==rankTab)return;$('leaderboard').innerHTML=rows.length?rows.map((r,i)=>'<div class="rank-row'+(r.user===session?.user?' you':'')+'"><span>'+(i+1)+'</span><strong>'+esc(r.name)+(tab==='learning'?levelBadge(r.score):'')+'</strong>'+(r.user===session?.user?'<small>YOU</small>':'')+'<span>'+r.score+(tab==='learning'?' XP':'')+'</span></div>').join(''):'No scores yet.';}catch(e){if(tab===rankTab)$('leaderboard').textContent=e.message;}}
$('wordForm').onsubmit=async e=>{e.preventDefault();if(!session||busy)return;busy=true;$('saveWord').disabled=true;const s=session;$('formMsg').classList.remove('hidden');$('formMsg').textContent='Saving...';try{await Q.auth(s.user,s.token);const word=$('wordInput').value.trim().toLowerCase(),meanings=$('meaningInput').value.split(/\n|\/|;/).map(v=>v.trim()).filter(Boolean),example=$('exampleInput').value.trim();if(!word||!meanings.length)throw Error('Enter a word and at least one meaning.');currentData=await Q.update(s.user,data=>{if(data.words.some(w=>w.word.toLowerCase()===word))throw Error('You already added this word.');data.words.push({id:Q.uid(),word,meanings,example,addedAt:new Date().toISOString(),addedDate:Q.day(),correct:0,wrong:0});data.xp=(data.xp||0)+5;});e.target.reset();$('formMsg').textContent='Saved! +5 XP.';}catch(err){$('formMsg').textContent=err.message;}finally{busy=false;$('saveWord').disabled=false;}};
function renderWords(){const q=$('searchInput').value.trim().toLowerCase(),words=[...(currentData?.words||[])].reverse().filter(w=>(w.word+' '+w.meanings.join(' ')).toLowerCase().includes(q));$('wordList').innerHTML=words.length?words.map(w=>'<div class="word"><div class="row"><strong>'+esc(w.word)+'</strong><span class="badge">'+mastery(w)+'</span></div><p>'+esc(w.meanings.join(' / '))+'</p>'+(w.example?'<p class="hint">'+esc(w.example)+'</p>':'')+'<div class="hint">'+(Q.correctToday(w)>=3?'Daily XP complete · Review only':' '+Q.correctToday(w)+'/3 correct today · XP available')+'</div>'+(Q.correctToday(w)>=3?'<p class="hint">You\'ve earned all XP for this word today. Keep reviewing, or add new words to earn more XP.</p>':'')+'</div>').join(''):'No words found.';}
$('searchInput').oninput=renderWords;
async function setupQuiz(){pending=null;retries=[];$('quizStart').classList.remove('hidden');$('quizPlay').classList.add('hidden');$('quizDone').classList.add('hidden');$('quizError').textContent='';$('beginQuiz').disabled=true;try{await Q.auth(session.user,session.token);currentData=Q.init(await Q.load(session.user));const count=currentData.words.length,earning=Q.eligible(currentData.words).length;const choices=count?(count>10?[5,10,15,20]:[10]):[];$('questionCount').replaceChildren();choices.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n+' questions';$('questionCount').append(o);});$('questionCount').value='10';$('countLabel').classList.toggle('hidden',currentData.words.length<=10);$('questionCount').classList.toggle('hidden',currentData.words.length<=10);$('eligibleInfo').textContent=!count?'Add your first word to begin.':!earning?'Review only — no XP available today. Add new words to earn more XP.':earning+' words can earn XP today. Repeated words fill the quiz when needed; each word earns XP for up to three correct answers per day.';$('beginQuiz').disabled=!count;}catch(e){$('quizError').textContent=e.message;}}
function chooseMode(w,previous){if(currentData.words.length<4)return 'spell';return Q.shuffle(['en-cn','cn-en','spell'].filter(m=>m!==previous))[0];}
function buildQuiz(words,count){if(!words.length)return [];const earning=Q.eligible(words),review=words.filter(w=>Q.correctToday(w)>=3),out=[],lastModes={};let pool=[...Q.pick(earning,earning.length),...Q.pick(review,review.length)];while(out.length<count){if(!pool.length)pool=[...Q.pick(earning,earning.length),...Q.pick(review,review.length)];const lastId=out[out.length-1]?.id;let index=pool.findIndex(w=>w.id!==lastId);if(index<0&&words.length>1){const alternatives=earning.filter(w=>w.id!==lastId);const w=Q.pick(alternatives.length?alternatives:words.filter(w=>w.id!==lastId),1)[0];pool.unshift(w);index=0;}if(index<0)index=0;const w=pool.splice(index,1)[0],mode=chooseMode(w,lastModes[w.id]);lastModes[w.id]=mode;out.push({id:w.id,mode});}return out;}
$('beginQuiz').onclick=async()=>{if(busy||!session)return;busy=true;$('beginQuiz').disabled=true;try{await Q.auth(session.user,session.token);currentData=Q.init(await Q.load(session.user));const pool=currentData.words,count=Number($('questionCount').value)||10;if(!pool.length)throw Error('Add your first word to begin.');quiz=buildQuiz(pool,count);quizIndex=0;results=[];retries=[];$('quizStart').classList.add('hidden');$('quizDone').classList.add('hidden');$('quizPlay').classList.remove('hidden');showQuestion();}catch(e){$('quizError').textContent=e.message;$('beginQuiz').disabled=false;}finally{busy=false;}};
function showQuestion(){clearInterval(timerId);const retry=retries.find(r=>r.due<=quizIndex);if(retry){const w=currentData.words.find(w=>w.id===retry.id);if(w&&!quiz.slice(quizIndex).some(q=>q.id===w.id))quiz[quizIndex]={id:w.id,mode:'spell'};retries=retries.filter(r=>r!==retry);}while(quizIndex<quiz.length){const w=currentData.words.find(w=>w.id===quiz[quizIndex].id);if(w)break;quizIndex++;}if(quizIndex>=quiz.length){finishQuiz();return;}const item=quiz[quizIndex],w=currentData.words.find(w=>w.id===item.id);item.w=w;item.attemptId=Q.uid();answered=false;hinted=false;pending=null;$('quizFeedback').classList.add('hidden');$('nextQuestion').classList.add('hidden');$('retryAnswer').classList.add('hidden');$('saveAnswerError').textContent='';$('hintButton').classList.remove('hidden');$('hintButton').disabled=false;$('hintButton').textContent='Show hint (no XP)';$('questionNumber').textContent='Question '+(quizIndex+1)+' / '+quiz.length;$('quizProgress').style.width=(quizIndex/quiz.length*100)+'%';$('quizOptions').replaceChildren();
if(item.mode==='spell'){$('quizType').textContent='Type the English word';$('quizQuestion').textContent=w.meanings.join(' / ');const input=document.createElement('input');input.id='spellAnswer';input.className='field';input.autocomplete='off';input.spellcheck=false;input.setAttribute('autocorrect','off');input.setAttribute('autocapitalize','none');input.setAttribute('aria-label','English answer');const button=document.createElement('button');button.className='btn primary';button.textContent='Check';const check=()=>answer(input.value.trim().toLowerCase()===w.word.toLowerCase());button.onclick=check;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();check();}};$('quizOptions').append(input,button);}
else{const en=item.mode==='en-cn',correct=en?w.meanings.join(' / '):w.word;$('quizType').textContent=en?'Choose the meaning':'Choose the English word';$('quizQuestion').textContent=en?w.word:w.meanings.join(' / ');const others=[...new Set(Q.shuffle(currentData.words.filter(v=>v.id!==w.id)).map(v=>en?v.meanings.join(' / '):v.word))].filter(v=>v!==correct).slice(0,3);Q.shuffle([correct,...others]).forEach(label=>{const b=document.createElement('button');b.className='option';b.textContent=label;b.dataset.correct=String(label===correct);b.onclick=()=>answer(label===correct,false,b);$('quizOptions').append(b);});}
if(Q.correctToday(w)>=3)$('quizType').textContent+=' / Review only · 0 XP';
deadline=Date.now()+Q.seconds(item.mode,w.word)*1000;tick();timerId=setInterval(tick,100);}
function tick(){if(answered)return;const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));$('timer').textContent=remaining+'s';$('timer').classList.toggle('urgent',remaining<=5);if(!remaining)answer(false,true);}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
$('hintButton').onclick=()=>{if(answered)return;hinted=true;$('hintButton').disabled=true;$('hintButton').textContent='Hint: '+(quiz[quizIndex].mode==='en-cn'?quiz[quizIndex].w.meanings[0]:quiz[quizIndex].w.word[0].toUpperCase()+'…')+' / This answer earns no XP.';};
async function answer(ok,timedOut=false,clicked){if(answered||busy)return;if(Date.now()>=deadline){ok=false;timedOut=true;}answered=true;clearInterval(timerId);$('hintButton').classList.add('hidden');$('quizOptions').querySelectorAll('button,input').forEach(el=>el.disabled=true);if(clicked)clicked.classList.add(ok?'correct':'wrong');if(!ok)$('quizOptions').querySelectorAll('[data-correct="true"]').forEach(el=>el.classList.add('correct'));pending={id:quiz[quizIndex].attemptId,wordId:quiz[quizIndex].id,ok,timedOut,hinted,date:Q.day(),at:new Date().toISOString()};await saveAnswer();}
async function saveAnswer(){if(!pending||busy)return;busy=true;$('retryAnswer').classList.add('hidden');$('quizFeedback').classList.remove('hidden');$('quizFeedback').textContent='Saving answer...';$('saveAnswerError').textContent='';const attempt=pending,s=session;try{await Q.auth(s.user,s.token);currentData=await Q.update(s.user,data=>{Q.recordAnswer(data,attempt);});const saved=currentData.answers[attempt.id],w=quiz[quizIndex].w;results.push({word:w.word,meanings:w.meanings,ok:attempt.ok,award:saved.award});$('quizFeedback').textContent=attempt.ok?'Correct! '+(saved.award?'+10 XP.':attempt.hinted?'Hint used / No XP.':'Daily XP limit reached / No XP.'):(attempt.timedOut?'Time is up. ':'Not quite. ')+'Answer: '+w.word+' / '+w.meanings.join(' / ');if(!attempt.ok&&quizIndex+3<quiz.length)retries.push({id:w.id,due:quizIndex+3});pending=null;$('nextQuestion').classList.remove('hidden');}catch(e){$('quizFeedback').textContent='Your answer is waiting to be saved.';$('saveAnswerError').textContent=e.message;$('retryAnswer').classList.remove('hidden');}finally{busy=false;}}
$('retryAnswer').onclick=saveAnswer;
$('nextQuestion').onclick=()=>{if(!busy&&!pending){quizIndex++;showQuestion();}};
function finishQuiz(){clearInterval(timerId);answered=true;$('quizPlay').classList.add('hidden');$('quizDone').classList.remove('hidden');const correct=results.filter(r=>r.ok).length,earned=results.reduce((n,r)=>n+r.award,0),wrong=results.filter(r=>!r.ok);$('quizDone').innerHTML='<h2>Quiz complete</h2><div class="xp">'+correct+' / '+results.length+'</div><p>'+earned+' XP earned</p>'+(wrong.length?'<h3>Words to review</h3>'+wrong.map(r=>'<div class="word"><strong>'+esc(r.word)+'</strong><p>'+esc(r.meanings.join(' / '))+'</p></div>').join(''):'<p>Great work! No missed words.</p>')+'<div class="actions"><button id="tryQuiz" class="btn primary">Try again</button><button id="quizHome" class="btn">Home</button></div>';$('tryQuiz').onclick=setupQuiz;$('quizHome').onclick=()=>show('home');}
window.addEventListener('pageshow',()=>{if(session&&!$('homeView').classList.contains('hidden'))refresh();});
(async()=>{try{const saved=JSON.parse(sessionStorage.getItem('questSession')||'null');if(saved){await Q.auth(saved.user,saved.token);session=saved;show('home');}else show('profiles');}catch{loggedOut();}})();
