'use strict';
window.MatchPractice=(()=>{
let phase='play',shuffleTimer=null,shuffleAnimations=[];
let mode='connect',round=[],cards=[],matched=new Set(),chosen=[],moves=0,earned=0,waiting=null,generation=0,closeTimer=null;
const queueKey='quest-matching-pending-v1';
let saveQueue=[],saving=false;
try{saveQueue=JSON.parse(localStorage.getItem(queueKey)||'[]');if(!Array.isArray(saveQueue))saveQueue=[];}catch{}
function persistQueue(){localStorage.setItem(queueKey,JSON.stringify(saveQueue.map(({user,attempt})=>({user,attempt}))));}
function saveStatus(){if($('matchView').classList.contains('hidden'))return;const n=saveQueue.filter(x=>x.user===session?.user).length;$('matchRetry').classList.toggle('hidden',!n||saving);if(!n)$('matchError').textContent='';else if(saving)$('matchError').textContent=n+' answer(s) saving · You can keep playing.';}
const label=w=>w.meanings.join(' / ');
function pairPool(words){const meanings=new Set(),english=new Set();return words.filter(w=>{if(!w.id||!w.word||!Array.isArray(w.meanings)||!w.meanings.length)return false;const m=label(w).trim().toLowerCase(),e=w.word.trim().toLowerCase();if(!m||meanings.has(m)||english.has(e))return false;meanings.add(m);english.add(e);return true;});}
function choosePairs(words,count){const pool=pairPool(words),earning=Q.eligible(pool),review=pool.filter(w=>Q.correctToday(w)>=3);return [...Q.pick(earning,earning.length),...Q.pick(review,review.length)].slice(0,count);}
function leave(){generation++;shuffleAnimations.forEach(a=>a.cancel());shuffleAnimations=[];$('matchBoard').classList.remove('shuffling');clearTimeout(closeTimer);clearTimeout(shuffleTimer);phase='closed';chosen=[];waiting=null;}
async function setup(){if(!session)return;void save();$('practiceInfo').textContent='Loading your words...';$('practiceError').textContent='';$('connectMode').disabled=$('memoryMode').disabled=true;const s=session;try{await Q.auth(s.user,s.token);const d=Q.init(await Q.load(s.user));if(session!==s||$('practiceView').classList.contains('hidden'))return;currentData=d;for(const feature of ['connect','memory'])$(feature+'New').classList.toggle('hidden',Q.featureSeen(d,feature));const n=pairPool(d.words).length;$('practiceInfo').textContent=d.words.length+' words in your vocabulary · '+n+' distinct pairs available.';$('connectMode').disabled=$('memoryMode').disabled=!n;if(!n)$('practiceInfo').textContent='Add a word with a meaning to start matching.';}catch(e){if(session===s)$('practiceError').textContent=e.message;}}
async function start(nextMode){if(!session||busy)return;void save();busy=true;const s=session;$('practiceError').textContent='';try{await Q.auth(s.user,s.token);const data=Q.init(await Q.load(s.user));if(session!==s)return;currentData=data;const selected=choosePairs(data.words,nextMode==='memory'?8:10);if(!selected.length)throw Error('Add a word with a meaning first.');if(!Q.featureSeen(data,nextMode)){currentData=await Q.markFeature(s.user,nextMode);if(session!==s)return;}$(nextMode+'New').classList.add('hidden');show('match');mode=nextMode;round=selected;matched=new Set();chosen=[];moves=0;earned=0;waiting=null;phase=mode==='memory'?'study':'play';cards=mode==='memory'?round.flatMap(w=>[{id:w.id,side:'en'},{id:w.id,side:'meaning'}]):[...Q.shuffle(round.map(w=>({id:w.id,side:'en'}))),...Q.shuffle(round.map(w=>({id:w.id,side:'meaning'})))];$('matchTitle').textContent=mode==='memory'?'Memory Match':'Meaning Connect';$('matchInstructions').textContent=mode==='memory'?'Study the word–meaning pairs, then hide and shuffle the cards.':'Choose a word or meaning, then find its pair.';$('matchFeedback').textContent=mode==='memory'?'Study every pair for as long as you like. Press Hide cards & shuffle when ready.':'No time limit. Take your time.';$('matchError').textContent='';$('matchRetry').classList.add('hidden');$('matchComplete').classList.add('hidden');}catch(e){$('practiceError').textContent=e.message;}finally{busy=false;render();}}
function render(){if($('matchView').classList.contains('hidden'))return;const board=$('matchBoard');board.replaceChildren();board.className=mode==='memory'?'memory-board':'match-columns';let en,meaning;if(mode==='connect'){en=document.createElement('div');meaning=document.createElement('div');for(const [col,title]of [[en,'ENGLISH'],[meaning,session?.user==='PARENT'?'MEANING':'中文']]){col.className='match-column';const tag=document.createElement('div');tag.className='match-label';tag.textContent=title;col.append(tag);board.append(col);}}
cards.forEach((c,index)=>{const w=round.find(w=>w.id===c.id),found=matched.has(c.id),open=mode==='connect'||phase==='study'||found||chosen.includes(index);const b=document.createElement('button');b.type='button';b.className='match-card'+(found?' matched':'')+(chosen.includes(index)?' selected':'')+(open&&mode==='memory'?' revealed':'');b.dataset.cardIndex=String(index);b.disabled=busy||!!waiting||found||(mode==='memory'&&phase!=='play');if(mode==='memory'&&open){const kind=document.createElement('span');kind.className='memory-kind';kind.textContent=c.side==='en'?'ENGLISH':'MEANING';const text=document.createElement('span');text.className='memory-content'+(c.side==='meaning'?' meaning-content':'');text.lang=c.side==='en'?'en':session?.user==='PARENT'?'ko':'zh-Hans';text.textContent=c.side==='en'?w.word:label(w);b.append(kind,text);if(found){const mark=document.createElement('small');mark.className='memory-matched';mark.textContent='✓ Matched';b.append(mark);}}else{b.textContent=open?(c.side==='en'?w.word:label(w)):'✦';if(open){const sub=document.createElement('small');sub.textContent=found?'✓ Matched':c.side==='en'?'English':'Meaning';b.append(sub);}}b.setAttribute('aria-label',open?(c.side==='en'?w.word:label(w))+(found?' matched':''):'Hidden card '+(index+1));b.onclick=()=>select(index);if(mode==='memory')board.append(b);else(c.side==='en'?en:meaning).append(b);});$('memoryBegin').classList.toggle('hidden',mode!=='memory'||phase!=='study');$('matchProgress').textContent=matched.size+' / '+round.length+' pairs';$('matchMoves').textContent=moves+' moves · '+earned+' XP';}
function closeWrong(){waiting={localOnly:true};render();const token=generation;closeTimer=setTimeout(()=>{if(token!==generation)return;chosen=[];waiting=null;render();},500);}
function select(index){if(busy||waiting||(mode==='memory'&&phase!=='play')||matched.has(cards[index].id)||chosen.includes(index))return;const c=cards[index];if(!chosen.length){chosen=[index];render();return;}const a=cards[chosen[0]];if(a.side===c.side&&mode==='memory'){chosen.push(index);moves++;$('matchFeedback').textContent='Not a pair. Look for a word and its meaning.';closeWrong();return;}if(a.side===c.side){chosen=[index];render();return;}
const attempt={id:Q.uid(),wordId:a.side==='en'?a.id:c.id,ok:a.id===c.id,hinted:false,date:Q.day(),at:new Date().toISOString()};
const item={user:session.user,attempt,version:generation};saveQueue.push(item);try{persistQueue();}catch{saveQueue.pop();$('matchError').textContent='Could not keep your answer safely. Please allow browser storage and try again.';return;}
chosen.push(index);moves++;const w=round.find(w=>w.id===attempt.wordId);
if(attempt.ok){matched.add(w.id);chosen=[];$('matchFeedback').textContent=w.word+' — '+label(w);speak(w.word);render();if(matched.size===round.length)complete();}
else{$('matchFeedback').textContent='Not a pair. '+w.word+' means '+label(w)+'.';if(mode==='memory')closeWrong();else{chosen=[];render();}}
void save();}
async function save(){if(saving||!session)return;const s=session;saving=true;saveStatus();try{
while(session===s){const batch=saveQueue.filter(x=>x.user===s.user);if(!batch.length)break;await Q.auth(s.user,s.token);const data=await Q.update(s.user,d=>{batch.forEach(x=>Q.recordAnswer(d,x.attempt));});
for(const x of batch){if(session===s&&x.version===generation){earned+=data.answers[x.attempt.id].award||0;}}
const ids=new Set(batch.map(x=>x.attempt.id));saveQueue=saveQueue.filter(x=>!ids.has(x.attempt.id));persistQueue();
if(session===s){currentData=data;if(phase==='play'){render();if(matched.size===round.length)complete();}}
}
}catch(e){if(session===s){$('matchError').textContent=e.message+' Answers are kept on this device. Retry saving.';}}
finally{saving=false;saveStatus();}}
function speak(word){try{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.85;window.speechSynthesis.speak(u);}catch{}}
function complete(){$('matchComplete').classList.remove('hidden');$('matchSummary').textContent=round.length+' pairs matched in '+moves+' moves · '+earned+' XP earned.';const review=$('matchReview');review.replaceChildren();round.forEach(w=>{const row=document.createElement('div');row.className='match-review-word';const heading=document.createElement('b');heading.textContent=w.word;const sound=document.createElement('button');sound.type='button';sound.className='match-speak';sound.textContent='Listen';sound.setAttribute('aria-label','Listen to '+w.word);sound.onclick=()=>speak(w.word);const m=document.createElement('p');m.textContent=label(w);row.append(heading,document.createTextNode(' '),sound,m);if(w.example){const example=document.createElement('p');example.className='hint';example.textContent=w.example;row.append(example);}review.append(row);});}
function shuffleDeck(){const before=cards;cards=Q.shuffle(cards);if(cards.length>1&&cards.every((c,i)=>c.id===before[i].id&&c.side===before[i].side))cards=[...cards.slice(1),cards[0]];}
async function animateCards(nodes,keyframes,options){const batch=nodes.map((node,i)=>node.animate(typeof keyframes==='function'?keyframes(node,i):keyframes,options));shuffleAnimations.push(...batch);await Promise.all(batch.map(a=>a.finished.catch(()=>{})));return batch;}
function pileTransforms(nodes){const box=$('matchBoard').getBoundingClientRect(),cx=box.left+box.width/2,cy=Math.max(box.top+80,Math.min(box.top+box.height/2,window.innerHeight-100));return nodes.map((node,i)=>{const r=node.getBoundingClientRect(),x=cx-r.left-r.width/2+(i%3-1)*4,y=cy-r.top-r.height/2+(i%4-1.5)*3;return {x,y,angle:(i%5-2)*3,transform:'translate('+x+'px,'+y+'px) scale(.78) rotate('+((i%5-2)*3)+'deg)'};});}
async function beginMemory(){
 if(mode!=='memory'||phase!=='study'||busy)return;
 const token=generation,board=$('matchBoard'),reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 phase='shuffle';$('memoryBegin').classList.add('hidden');$('matchInstructions').textContent='Cards are being shuffled...';$('matchFeedback').textContent='Hiding the cards...';
 let nodes=[...board.querySelectorAll('.match-card')];nodes.forEach(b=>b.disabled=true);
 try{
  if(!reduced&&nodes.every(n=>typeof n.animate==='function')){
   await animateCards(nodes,[{transform:'perspective(700px) rotateY(0deg)'},{transform:'perspective(700px) rotateY(90deg)'}],{duration:140,easing:'ease-in',fill:'forwards'});if(token!==generation)return;
   shuffleAnimations.forEach(a=>a.cancel());shuffleAnimations=[];render();nodes=[...board.querySelectorAll('.match-card')];
   await animateCards(nodes,[{transform:'perspective(700px) rotateY(-90deg)'},{transform:'perspective(700px) rotateY(0deg)'}],{duration:140,easing:'ease-out'});if(token!==generation)return;
   board.classList.add('shuffling');$('matchFeedback').textContent='Gathering and mixing the cards...';const pile=pileTransforms(nodes);
   nodes.forEach((n,i)=>n.style.zIndex=String(i+1));
   await animateCards(nodes,(n,i)=>[{transform:'translate(0,0) scale(1) rotate(0deg)'},{transform:pile[i].transform}],{duration:330,easing:'cubic-bezier(.4,0,.2,1)',fill:'forwards'});if(token!==generation)return;
   await animateCards(nodes,(n,i)=>{const p=pile[i],direction=i%2?1:-1;return [{transform:p.transform},{transform:'translate('+(p.x+direction*35)+'px,'+(p.y-12)+'px) scale(.78) rotate('+(p.angle+direction*9)+'deg)'},{transform:p.transform}];},{duration:320,easing:'ease-in-out',fill:'forwards'});if(token!==generation)return;
   shuffleAnimations.forEach(a=>a.cancel());shuffleAnimations=[];shuffleDeck();render();nodes=[...board.querySelectorAll('.match-card')];const spread=pileTransforms(nodes);$('matchFeedback').textContent='Dealing the shuffled cards...';
   await animateCards(nodes,(n,i)=>[{transform:spread[i].transform},{transform:'translate(0,0) scale(1) rotate(0deg)'}],{duration:360,easing:'cubic-bezier(.2,.7,.2,1)'});if(token!==generation)return;
  }else{shuffleDeck();}
 }catch{if(token!==generation)return;shuffleDeck();}
 if(token!==generation)return;
 shuffleAnimations.forEach(a=>a.cancel());shuffleAnimations=[];board.classList.remove('shuffling');phase='play';$('matchInstructions').textContent='Turn over any two cards. Find the word–meaning pairs.';$('matchFeedback').textContent='All card backs are identical. Find every pair!';render();
}
$('memoryBegin').onclick=beginMemory;
$('connectMode').onclick=()=>start('connect');$('memoryMode').onclick=()=>start('memory');$('matchRetry').onclick=save;$('matchAgain').onclick=()=>start(mode);
return {setup,leave,pairPool,choosePairs};
})();
