'use strict';
window.MatchPractice=(()=>{
let phase='play',shuffleTimer=null;
let mode='connect',round=[],cards=[],matched=new Set(),chosen=[],moves=0,earned=0,waiting=null,generation=0,closeTimer=null;
const label=w=>w.meanings.join(' / ');
function pairPool(words){const meanings=new Set(),english=new Set();return words.filter(w=>{if(!w.id||!w.word||!Array.isArray(w.meanings)||!w.meanings.length)return false;const m=label(w).trim().toLowerCase(),e=w.word.trim().toLowerCase();if(!m||meanings.has(m)||english.has(e))return false;meanings.add(m);english.add(e);return true;});}
function choosePairs(words,count){const pool=pairPool(words),earning=Q.eligible(pool),review=pool.filter(w=>Q.correctToday(w)>=3);return [...Q.pick(earning,earning.length),...Q.pick(review,review.length)].slice(0,count);}
function leave(){generation++;clearTimeout(closeTimer);clearTimeout(shuffleTimer);phase='closed';chosen=[];waiting=null;}
async function setup(){if(!session)return;$('practiceInfo').textContent='Loading your words...';$('practiceError').textContent='';$('connectMode').disabled=$('memoryMode').disabled=true;const s=session;try{await Q.auth(s.user,s.token);const d=Q.init(await Q.load(s.user));if(session!==s||$('practiceView').classList.contains('hidden'))return;currentData=d;const n=pairPool(d.words).length;$('practiceInfo').textContent=d.words.length+' words in your vocabulary · '+n+' distinct pairs available.';$('connectMode').disabled=$('memoryMode').disabled=!n;if(!n)$('practiceInfo').textContent='Add a word with a meaning to start matching.';}catch(e){if(session===s)$('practiceError').textContent=e.message;}}
async function start(nextMode){if(!session||busy)return;busy=true;const s=session;$('practiceError').textContent='';try{await Q.auth(s.user,s.token);const data=Q.init(await Q.load(s.user));if(session!==s)return;currentData=data;const selected=choosePairs(data.words,Number($('pairCount').value)||4);if(!selected.length)throw Error('Add a word with a meaning first.');show('match');mode=nextMode;round=selected;matched=new Set();chosen=[];moves=0;earned=0;waiting=null;phase=mode==='memory'?'study':'play';cards=mode==='memory'?round.flatMap(w=>[{id:w.id,side:'en'},{id:w.id,side:'meaning'}]):[...Q.shuffle(round.map(w=>({id:w.id,side:'en'}))),...Q.shuffle(round.map(w=>({id:w.id,side:'meaning'})))];$('matchTitle').textContent=mode==='memory'?'Memory Match':'Meaning Connect';$('matchInstructions').textContent=mode==='memory'?'Study the word–meaning pairs, then hide and shuffle the cards.':'Choose an English word, then its meaning.';$('matchFeedback').textContent=mode==='memory'?'Study every pair for as long as you like. Press Hide cards & shuffle when ready.':'No time limit. Take your time.';$('matchError').textContent='';$('matchRetry').classList.add('hidden');$('matchComplete').classList.add('hidden');}catch(e){$('practiceError').textContent=e.message;}finally{busy=false;render();}}
function render(){if($('matchView').classList.contains('hidden'))return;const board=$('matchBoard');board.replaceChildren();board.className=mode==='memory'?'memory-board':'match-columns';let en,meaning;if(mode==='connect'){en=document.createElement('div');meaning=document.createElement('div');for(const [col,title]of [[en,'ENGLISH'],[meaning,session?.user==='PARENT'?'MEANING':'中文']]){col.className='match-column';const tag=document.createElement('div');tag.className='match-label';tag.textContent=title;col.append(tag);board.append(col);}}
cards.forEach((c,index)=>{const w=round.find(w=>w.id===c.id),found=matched.has(c.id),open=mode==='connect'||phase==='study'||found||chosen.includes(index);const b=document.createElement('button');b.type='button';b.className='match-card'+(found?' matched':'')+(chosen.includes(index)?' selected':'')+(open&&mode==='memory'?' revealed':'');b.dataset.cardIndex=String(index);b.disabled=busy||!!waiting||found||(mode==='memory'&&phase!=='play');if(mode==='memory'&&open){const kind=document.createElement('span');kind.className='memory-kind';kind.textContent=c.side==='en'?'ENGLISH':'MEANING';const text=document.createElement('span');text.className='memory-content'+(c.side==='meaning'?' meaning-content':'');text.lang=c.side==='en'?'en':session?.user==='PARENT'?'ko':'zh-Hans';text.textContent=c.side==='en'?w.word:label(w);b.append(kind,text);if(found){const mark=document.createElement('small');mark.className='memory-matched';mark.textContent='✓ Matched';b.append(mark);}}else{b.textContent=open?(c.side==='en'?w.word:label(w)):'✦';if(open){const sub=document.createElement('small');sub.textContent=found?'✓ Matched':c.side==='en'?'English':'Meaning';b.append(sub);}}b.setAttribute('aria-label',open?(c.side==='en'?w.word:label(w))+(found?' matched':''):'Hidden card '+(index+1));b.onclick=()=>select(index);if(mode==='memory')board.append(b);else(c.side==='en'?en:meaning).append(b);});$('memoryBegin').classList.toggle('hidden',mode!=='memory'||phase!=='study');$('matchProgress').textContent=matched.size+' / '+round.length+' pairs';$('matchMoves').textContent=moves+' moves · '+earned+' XP';}
async function select(index){if(busy||waiting||(mode==='memory'&&phase!=='play')||matched.has(cards[index].id)||chosen.includes(index))return;const c=cards[index];if(!chosen.length){if(mode==='connect'&&c.side!=='en'){$('matchFeedback').textContent='Choose an English word first.';return;}chosen=[index];render();return;}const a=cards[chosen[0]];if(a.side===c.side&&mode==='memory'){chosen.push(index);moves++;waiting={localOnly:true};$('matchFeedback').textContent='Not a pair. Look for a word and its meaning.';render();const token=generation;closeTimer=setTimeout(()=>{if(token!==generation)return;chosen=[];waiting=null;render();},1100);return;}if(a.side===c.side){chosen=[index];$('matchFeedback').textContent='Now choose a '+(c.side==='en'?'meaning':'word')+' card.';render();return;}chosen.push(index);moves++;const wordId=a.side==='en'?a.id:c.id;waiting={id:Q.uid(),wordId,ok:a.id===c.id,hinted:false,date:Q.day(),at:new Date().toISOString()};await save();}
async function save(){if(!waiting||busy||!session)return;busy=true;const attempt=waiting,s=session,version=generation;render();$('matchError').textContent='';$('matchRetry').classList.add('hidden');$('matchFeedback').textContent='Saving your answer...';try{await Q.auth(s.user,s.token);const data=await Q.update(s.user,d=>Q.recordAnswer(d,attempt));if(session!==s||version!==generation)return;currentData=data;const result=data.answers[attempt.id],w=round.find(w=>w.id===attempt.wordId);if(attempt.ok){matched.add(w.id);earned+=result.award;chosen=[];$('matchFeedback').textContent=w.word+' — '+label(w)+(result.award?' · +10 XP':' · Review only, no XP left for this word today.');speak(w.word);}else{$('matchFeedback').textContent='Not a pair. '+w.word+' means '+label(w)+'.';if(mode==='memory'){const token=generation;closeTimer=setTimeout(()=>{if(token!==generation)return;chosen=[];waiting=null;render();},1100);}else chosen=[];}if(attempt.ok||mode!=='memory')waiting=null;if(matched.size===round.length)complete();}catch(e){if(version===generation){$('matchError').textContent=e.message;$('matchFeedback').textContent='Your answer is waiting to be saved. Retry without losing this round.';$('matchRetry').classList.remove('hidden');}}finally{busy=false;render();}}
function speak(word){try{if(!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-US';u.rate=.85;window.speechSynthesis.speak(u);}catch{}}
function complete(){$('matchComplete').classList.remove('hidden');$('matchSummary').textContent=round.length+' pairs matched in '+moves+' moves · '+earned+' XP earned.';const review=$('matchReview');review.replaceChildren();round.forEach(w=>{const row=document.createElement('div');row.className='match-review-word';const heading=document.createElement('b');heading.textContent=w.word;const sound=document.createElement('button');sound.type='button';sound.className='match-speak';sound.textContent='Listen';sound.setAttribute('aria-label','Listen to '+w.word);sound.onclick=()=>speak(w.word);const m=document.createElement('p');m.textContent=label(w);row.append(heading,document.createTextNode(' '),sound,m);if(w.example){const example=document.createElement('p');example.className='hint';example.textContent=w.example;row.append(example);}review.append(row);});}
function beginMemory(){if(mode!=='memory'||phase!=='study'||busy)return;phase='shuffle';$('matchInstructions').textContent='Cards are hidden. Shuffling...';$('matchFeedback').textContent='Shuffling the deck...';render();const token=generation;shuffleTimer=setTimeout(()=>{if(token!==generation)return;const before=cards;cards=Q.shuffle(cards);if(cards.length>1&&cards.every((c,i)=>c.id===before[i].id&&c.side===before[i].side))cards=[...cards.slice(1),cards[0]];phase='play';$('matchInstructions').textContent='Turn over any two cards. Find the word–meaning pairs.';$('matchFeedback').textContent='All card backs are identical. Find every pair!';render();},650);}
$('memoryBegin').onclick=beginMemory;
$('connectMode').onclick=()=>start('connect');$('memoryMode').onclick=()=>start('memory');$('matchRetry').onclick=save;$('matchAgain').onclick=()=>start(mode);
return {setup,leave,pairPool,choosePairs};
})();
