'use strict';
const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),keys=new Set();
let scale=1,walkDirection=0,x=150,state='ready',score=0,best=0,elapsed=0,spawn=0,items=[],last=0,clock=0,pointer=null,lastTouch=0,latestId=null,saving=false,submission=null;
const BASE='https://mantledb.sh/v2',NS='dy-poop-dodge-79ae04b9-021f-4208-aec7-46c68d01e86f';
const Q=window.Quest,query=new URLSearchParams(location.search);
let gameSession=null,gateReady=false,starting=false,quota=null,pendingStart=null;
try{gameSession=query.has('token')?{user:query.get('user'),token:query.get('token')}:JSON.parse(sessionStorage.getItem('questGameSession')||'null');if(gameSession)sessionStorage.setItem('questGameSession',JSON.stringify(gameSession));history.replaceState(null,'',location.pathname);}catch{}
let lastQuotaDay=Q.day();
setInterval(()=>{if(gameSession&&Q.day()!==lastQuotaDay){lastQuotaDay=Q.day();checkQuota().catch(()=>{gateReady=false;quotaUI()});}},30000);
function quotaUI(){const allowed=gateReady&&(quota?.canPlay||(pendingStart&&quota?.lastStart===pendingStart))&&!starting;for(const id of ['start','skip','playAgain'])$(id).disabled=!allowed;$('playStatus').textContent=!gateReady?'Sign in from the learning app to play.':quota.used>=6?'Daily limit reached. Come back tomorrow!':!quota.remaining?'No plays left. Keep learning to earn more plays.':quota.available+' plays left / '+quota.used+'/6 played today';}
async function checkQuota(){if(!gameSession)throw Error('Please sign in from the learning app.');quota=await Q.status(gameSession.user,gameSession.token);gateReady=true;quotaUI();}
$('returnLearning').onclick=()=>location.href=Q.HOME;
const compare=(a,b)=>b.score-a.score||a.at-b.at||a.id.localeCompare(b.id);
const valid=r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.name.length<=20&&Number.isInteger(r.score)&&r.score>=0&&r.score<=10000000&&Number.isFinite(r.at);
async function request(url,options={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{return await fetch(url,{...options,signal:c.signal,cache:'no-store'})}finally{clearTimeout(t)}}
async function loadBucket(i){const r=await request(`${BASE}/${NS}/scores-${i}`);if(r.status===404)return {};if(!r.ok)throw Error('Could not load online scores. Please try again.');return r.json()}
async function loadScores(){const buckets=await Promise.all([0,1,2,3].map(loadBucket));const rows=buckets.flatMap(b=>Object.values(b).filter(r=>valid(r)&&r.user!=='PARENT'&&!/^parent(?:\s|$)/i.test(r.name))).sort(compare);best=rows[0]?.score||0;$('storageStatus').textContent='Shared online leaderboard';return rows.slice(0,10)}
async function saveRecord(record){const bucket=parseInt(record.id.replace(/-/g,'').slice(0,2),16)%4;const old=await loadBucket(bucket);const candidates=[...Object.values(old).filter(valid).filter(r=>r.id!==record.id),record].sort(compare);const patch={[record.id]:record};for(const r of candidates.slice(10)){if(r.id!==record.id)patch[r.id]=null}const r=await request(BASE+'/'+NS+'/scores-'+bucket,{method:Object.keys(old).length?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!r.ok)throw Error('Could not save your score ('+r.status+'). Please try again.');latestId=record.id;return loadScores()}
function overlays(){for(const [id,s]of [['startOverlay','ready'],['pauseOverlay','paused'],['deathOverlay','dead']])$(id).classList.toggle('hidden',state!==s)}
function resetGame(){state=window.matchMedia('(pointer:coarse)').matches?'paused':'running';x=150;score=0;elapsed=0;spawn=0;items=[];walkDirection=0;pointer=null;keys.clear();submission=null;latestId=null;$('gameView').classList.remove('hidden');$('leaderView').classList.add('hidden');$('saveError').textContent='';overlays();canvas.focus()}
async function startGame(){if(starting||!gateReady)return;starting=true;quotaUI();try{pendingStart=pendingStart||Q.uid();quota=await Q.start(gameSession.user,gameSession.token,pendingStart);pendingStart=null;resetGame();$('playerName').value=gameSession.user==='PARENT'?'Parent':gameSession.user[0]+gameSession.user.slice(1).toLowerCase();$('playerName').readOnly=true;}catch(e){$('playStatus').textContent=e.message;try{await checkQuota()}catch{gateReady=false}}finally{starting=false;quotaUI();}}
function pause(){if(state!=='running')return;state='paused';keys.clear();walkDirection=0;pointer=null;overlays()}
function resume(){if(state!=='paused')return;state='running';overlays()}
function die(){state='dead';keys.clear();pointer=null;walkDirection=0;$('finalScore').textContent=score;overlays();setTimeout(()=>$('playerName').focus(),0)}
function collides(p){const left=p.x-8,right=p.x+10,top=p.y-9.6,bottom=p.y+5.6;return right>x-4&&left<x+5&&bottom>370&&top<398}
function draw(){ctx.clearRect(0,0,300,400);ctx.fillStyle='#48443f';ctx.font='14px monospace';ctx.fillText(String(best),2,17);ctx.fillText(String(score),2,33);ctx.font='8px monospace';ctx.fillStyle='#777';ctx.fillText('BEST',65,17);ctx.fillText('SCORE',65,33);items.forEach(p=>poop(p.x,p.y));ctx.strokeStyle='#77736c';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,398);ctx.lineTo(300,398);ctx.stroke();character(x,397,clock)}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(state==='running'){clock+=dt;elapsed+=dt;const axis=Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'));if(pointer===null){walkDirection=axis;x+=axis*145*dt}else if(now-lastTouch>100)walkDirection=0;x=Math.max(8,Math.min(292,x));const level=Math.min(elapsed/30,5);spawn+=dt;while(spawn>=Math.max(.14,.55-level*.07)){spawn-=Math.max(.14,.55-level*.07);items.push({x:12+Math.random()*276,y:-18,speed:70+level*18+Math.random()*35})}for(const p of items){p.y+=p.speed*dt;if(collides(p)){die();break}if(p.y>410&&!p.passed){p.passed=true;score++}}items=items.filter(p=>p.y<420)}draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button')&&e.code!=='Space')return;if(e.target.matches('input,textarea'))return;if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(state==='running')pause();else if(state==='paused')resume();else if(state==='ready'&&!$('gameView').classList.contains('hidden'))startGame()}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();if(state==='running')keys.add(e.key)}});
window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
const playfield=canvas.parentElement;
let touchOffset=0;
function touchX(e){const rect=canvas.getBoundingClientRect();return (e.clientX-rect.left)/rect.width*300}
function moveTouch(e){const next=Math.max(8,Math.min(292,touchX(e)+touchOffset));walkDirection=Math.sign(next-x);x=next;lastTouch=performance.now()}
function beginTouch(e){if(e.pointerType==='mouse'||!['running','paused'].includes(state)||pointer!==null||e.target.closest('button,input'))return;e.preventDefault();pointer=e.pointerId;touchOffset=x-touchX(e);try{playfield.setPointerCapture(e.pointerId)}catch{}resume();lastTouch=performance.now()}
function release(e){if(e.pointerId===pointer){e.preventDefault?.();pause()}}
if('PointerEvent' in window){
playfield.addEventListener('pointerdown',beginTouch);
playfield.addEventListener('pointermove',e=>{if(e.pointerId===pointer&&state==='running'){e.preventDefault();moveTouch(e)}});
for(const name of ['pointerup','pointercancel','lostpointercapture'])playfield.addEventListener(name,release);
window.addEventListener('pointerup',release);window.addEventListener('pointercancel',release);
}else{
playfield.addEventListener('touchstart',e=>{if(pointer!==null||!e.changedTouches.length)return;const t=e.changedTouches[0];beginTouch({pointerId:t.identifier,pointerType:'touch',clientX:t.clientX,target:e.target,preventDefault:()=>e.preventDefault()})},{passive:false});
playfield.addEventListener('touchmove',e=>{const t=Array.from(e.changedTouches).find(t=>t.identifier===pointer);if(t&&state==='running'){e.preventDefault();moveTouch(t)}},{passive:false});
for(const name of ['touchend','touchcancel'])window.addEventListener(name,e=>{if(Array.from(e.changedTouches).some(t=>t.identifier===pointer))release({pointerId:pointer,preventDefault:()=>e.preventDefault()})},{passive:false});
}
$('start').onclick=startGame;$('resume').onclick=resume;$('skip').onclick=startGame;$('playAgain').onclick=startGame;
function renderRanking(rows){const body=$('ranking');body.replaceChildren();rows.forEach((r,i)=>{const tr=document.createElement('tr');tr.classList.toggle('you',r.id===latestId);for(const text of [String(i+1),r.name,String(r.score)]){const td=document.createElement('td');td.textContent=text;tr.append(td)}if(r.id===latestId){const mark=document.createElement('small');mark.textContent='YOU';tr.children[1].append(mark)}body.append(tr)});if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.className='empty';td.textContent='No scores yet. Be the first!';tr.append(td);body.append(tr)}$('rankNote').textContent=latestId&&!rows.some(r=>r.id===latestId)?'Your score was saved. Keep playing to reach the top 10.':''}
async function showLeaderboard(rows){pause();$('gameView').classList.add('hidden');$('leaderView').classList.remove('hidden');$('back').classList.toggle('hidden',!['ready','paused'].includes(state));$('leaderError').textContent='';if(rows){renderRanking(rows);return}$('rankNote').textContent='Loading scores...';try{renderRanking(await loadScores())}catch(e){$('rankNote').textContent='';$('leaderError').textContent=e.message}}
$('openLeaderboard').onclick=()=>showLeaderboard();$('refreshScores').onclick=()=>showLeaderboard();$('back').onclick=()=>{$('leaderView').classList.add('hidden');$('gameView').classList.remove('hidden');overlays()};
$('scoreForm').onsubmit=async e=>{e.preventDefault();if(saving||state!=='dead')return;const name=gameSession?.user==='PARENT'?'Parent':gameSession?.user?gameSession.user[0]+gameSession.user.slice(1).toLowerCase():'';if(!name){$('saveError').textContent='Please enter your name.';return}saving=true;$('save').disabled=true;$('save').textContent='SAVING...';$('saveError').textContent='';submission= submission||{id:crypto.randomUUID(),name,score,at:Date.now(),user:gameSession.user};submission.name=name;try{await Q.auth(gameSession.user,gameSession.token);if(gameSession.user==='PARENT'){await showLeaderboard(await loadScores());$('rankNote').textContent='Parent test score: '+score+' / Excluded from the leaderboard.';}else{const rows=await saveRecord(submission);await showLeaderboard(rows);}await checkQuota()}catch(err){$('saveError').textContent=err.message||'Could not save your score. Please try again.'}finally{saving=false;$('save').disabled=false;$('save').textContent='SAVE SCORE'}};
checkQuota().catch(e=>{gateReady=false;quotaUI();$('playStatus').textContent=e.message;});
loadScores().catch(()=>{$('storageStatus').textContent='Online scores unavailable. You can still play.'});requestAnimationFrame(frame);