'use strict';
const canvas=document.getElementById('scene'),ctx=canvas.getContext('2d');
const $=id=>document.getElementById(id),keys=new Set();
let scale=1,walkDirection=0,x=150,state='ready',score=0,best=0,elapsed=0,spawn=0,items=[],last=0,clock=0,pointer=null,lastTouch=0,latestId=null,saving=false,submission=null;
const BASE='https://mantledb.sh/v2',NS='dy-poop-dodge-79ae04b9-021f-4208-aec7-46c68d01e86f';
const compare=(a,b)=>b.score-a.score||a.at-b.at||a.id.localeCompare(b.id);
const valid=r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.name.length<=20&&Number.isInteger(r.score)&&r.score>=0&&r.score<=10000000&&Number.isFinite(r.at);
async function request(url,options={}){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{return await fetch(url,{...options,signal:c.signal,cache:'no-store'})}finally{clearTimeout(t)}}
async function loadBucket(i){const r=await request(`${BASE}/${NS}/scores-${i}`);if(r.status===404)return {};if(!r.ok)throw Error('Could not load online scores. Please try again.');return r.json()}
async function loadScores(){const buckets=await Promise.all([0,1,2,3].map(loadBucket));const rows=buckets.flatMap(b=>Object.values(b).filter(valid)).sort(compare);best=rows[0]?.score||0;$('storageStatus').textContent='Shared online leaderboard';return rows.slice(0,10)}
async function saveRecord(record){const bucket=parseInt(record.id.replace(/-/g,'').slice(0,2),16)%4;const old=await loadBucket(bucket);const candidates=[...Object.values(old).filter(valid).filter(r=>r.id!==record.id),record].sort(compare);const patch={[record.id]:record};for(const r of candidates.slice(10)){if(r.id!==record.id)patch[r.id]=null}const r=await request(BASE+'/'+NS+'/scores-'+bucket,{method:Object.keys(old).length?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});if(!r.ok)throw Error('Could not save your score ('+r.status+'). Please try again.');latestId=record.id;return loadScores()}
function overlays(){for(const [id,s]of [['startOverlay','ready'],['pauseOverlay','paused'],['deathOverlay','dead']])$(id).classList.toggle('hidden',state!==s)}
function startGame(){state=window.matchMedia('(pointer:coarse)').matches?'paused':'running';x=150;score=0;elapsed=0;spawn=0;items=[];walkDirection=0;pointer=null;keys.clear();submission=null;latestId=null;$('gameView').classList.remove('hidden');$('leaderView').classList.add('hidden');$('saveError').textContent='';overlays();canvas.focus()}
function pause(){if(state!=='running')return;state='paused';keys.clear();walkDirection=0;pointer=null;overlays()}
function resume(){if(state!=='paused')return;state='running';overlays()}
function die(){state='dead';keys.clear();pointer=null;walkDirection=0;$('finalScore').textContent=score;overlays();setTimeout(()=>$('playerName').focus(),0)}
function collides(p){const left=p.x-8,right=p.x+10,top=p.y-9.6,bottom=p.y+5.6;return right>x-4&&left<x+5&&bottom>370&&top<398}
function draw(){ctx.clearRect(0,0,300,400);ctx.fillStyle='#48443f';ctx.font='14px monospace';ctx.fillText(String(best),2,17);ctx.fillText(String(score),2,33);ctx.font='8px monospace';ctx.fillStyle='#777';ctx.fillText('BEST',65,17);ctx.fillText('SCORE',65,33);items.forEach(p=>poop(p.x,p.y));ctx.strokeStyle='#77736c';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,398);ctx.lineTo(300,398);ctx.stroke();character(x,397,clock)}
function frame(now){const dt=Math.min((now-last)/1000||0,.04);last=now;if(state==='running'){clock+=dt;elapsed+=dt;const axis=Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'));if(pointer===null){walkDirection=axis;x+=axis*145*dt}else if(now-lastTouch>100)walkDirection=0;x=Math.max(8,Math.min(292,x));const level=Math.min(elapsed/30,5);spawn+=dt;while(spawn>=Math.max(.14,.55-level*.07)){spawn-=Math.max(.14,.55-level*.07);items.push({x:12+Math.random()*276,y:-18,speed:70+level*18+Math.random()*35})}for(const p of items){p.y+=p.speed*dt;if(collides(p)){die();break}if(p.y>410&&!p.passed){p.passed=true;score++}}items=items.filter(p=>p.y<420)}draw();requestAnimationFrame(frame)}
window.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button')&&e.code!=='Space')return;if(e.target.matches('input,textarea'))return;if(e.code==='Space'){e.preventDefault();if(e.repeat)return;if(state==='running')pause();else if(state==='paused')resume();else if(state==='ready'&&!$('gameView').classList.contains('hidden'))startGame()}if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();if(state==='running')keys.add(e.key)}});
window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function moveTouch(e){const rect=canvas.getBoundingClientRect(),next=Math.max(8,Math.min(292,(e.clientX-rect.left)/rect.width*300));walkDirection=Math.sign(next-x);x=next;lastTouch=performance.now()}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||!['running','paused'].includes(state)||pointer!==null)return;e.preventDefault();resume();pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);moveTouch(e)});
canvas.addEventListener('pointermove',e=>{if(e.pointerId===pointer&&state==='running')moveTouch(e)});
function release(e){if(e.pointerId===pointer)pause()}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',release);
// The pause layer must pass a new touch into the playfield, without moving on a mouse click.
$('pauseOverlay').addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.target.closest('button'))return;e.preventDefault();resume();pointer=e.pointerId;canvas.setPointerCapture(e.pointerId);moveTouch(e)});
$('start').onclick=startGame;$('resume').onclick=resume;$('skip').onclick=startGame;$('playAgain').onclick=startGame;
function renderRanking(rows){const body=$('ranking');body.replaceChildren();rows.forEach((r,i)=>{const tr=document.createElement('tr');tr.classList.toggle('you',r.id===latestId);for(const text of [String(i+1),r.name,String(r.score)]){const td=document.createElement('td');td.textContent=text;tr.append(td)}if(r.id===latestId){const mark=document.createElement('small');mark.textContent='YOU';tr.children[1].append(mark)}body.append(tr)});if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=3;td.className='empty';td.textContent='No scores yet. Be the first!';tr.append(td);body.append(tr)}$('rankNote').textContent=latestId&&!rows.some(r=>r.id===latestId)?'Your score was saved. Keep playing to reach the top 10.':''}
async function showLeaderboard(rows){pause();$('gameView').classList.add('hidden');$('leaderView').classList.remove('hidden');$('back').classList.toggle('hidden',!['ready','paused'].includes(state));$('leaderError').textContent='';if(rows){renderRanking(rows);return}$('rankNote').textContent='Loading scores...';try{renderRanking(await loadScores())}catch(e){$('rankNote').textContent='';$('leaderError').textContent=e.message}}
$('openLeaderboard').onclick=()=>showLeaderboard();$('refreshScores').onclick=()=>showLeaderboard();$('back').onclick=()=>{$('leaderView').classList.add('hidden');$('gameView').classList.remove('hidden');overlays()};
$('scoreForm').onsubmit=async e=>{e.preventDefault();if(saving||state!=='dead')return;const name=$('playerName').value.trim().replace(/[\u0000-\u001f\u007f]/g,'').slice(0,20);if(!name){$('saveError').textContent='Please enter your name.';return}saving=true;$('save').disabled=true;$('save').textContent='SAVING...';$('saveError').textContent='';submission= submission||{id:crypto.randomUUID(),name,score,at:Date.now()};submission.name=name;try{const rows=await saveRecord(submission);await showLeaderboard(rows)}catch(err){$('saveError').textContent=err.message||'Could not save your score. Please try again.'}finally{saving=false;$('save').disabled=false;$('save').textContent='SAVE SCORE'}};
loadScores().catch(()=>{$('storageStatus').textContent='Online scores unavailable. You can still play.'});requestAnimationFrame(frame);